### ISSUE TITLE
Directional coin displays wrong graphics while blue POW switch is active

### ISSUE THREAD

**Issue by NewPointless** [TheLX5/DynamicSpritesetSystem#10]
![OldSchool-210705-154111](https://user-images.githubusercontent.com/86983620/124512882-7bba0e80-dda7-11eb-8255-29f32a541b7f.png)

**Comment by TheLX5** [comment]
Hmmm how strange. The directional coins graphics don't use DSS. Can you check if it's using graphics from SP1 and the ROM you're using has the used block graphics in?

![image](https://user-images.githubusercontent.com/17969056/125695620-06c941dc-3ba9-4eb6-ba94-1ca82349ff73.png)

**Comment by TheLX5** [comment]
Never mind, I forgot to add DSS support to that sprite and the file on my workspace is outdated... but not the one on GitHub. It'll be fixed on the next release.

**Comment by TheLX5** [comment]
Fixed on https://github.com/TheLX5/DynamicSpritesetSystem/commit/ee38726ee8fead0769e372e1eced6763c0363fc2
